
export type OneCallData = {
    daily:{
            clouds:number;
            dew_point:number;
            dt:number;
            feels_like:{
                day:number;
                night:number;
                eve:number;
                morn:number;
            }
            humidity:number;
            moon_phase:number;
            moonrise:number;
            mooset:number;
            pop:number;
            pressure:number;
            snow?:number;
            sunrise:number;
            suset:number;
            temp:{
                day:number;
                eve:number;
                max:number;
                min:number;
                morn:number;
                night:number;
            }
            uvi:number;
            weather:[
                        {
                            description:string;
                            icon:string;
                            id:number;
                            main:string;
                        }
            ]
            wind_deg:number;
            wind_gust:number;
            wind_speed:number;
        }[]
    hourly:[
            {
                clouds:number;
                dew_point:number;
                dt:number;
                feels_like:number;
                humidity:number;
                pop:number;
                pressure:number;
                temp:number;
                uvi:number;
                visibility:number;
                weather:[
                         {
                            id:number;
                            main:string;
                            description:string;
                            icon:string;
                }
            ]
            wind_deg:number;
            wind_gust:number;
            wind_speed:number
            }
    ]   
    lat:number ;
    lon:number ;
    timezone:string ;
    timezone_offset:number ;
}